name: Deploy Angular App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build Angular App
      run: npm run build

    - name: Upload dist folder to EC2 via rsync
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key" dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/angular-app

    - name: Restart Nginx on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: sudo systemctl restart nginx
